version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Backend
hooks:
  BeforeInstall:
    - location: scripts/application_stop.sh
      timeout: 900
      runas: root
  AfterInstall:
    - location: scripts/before_install.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 900
      runas: root