module.exports = {
    en: {
        USERFOUND: "User found",
        ADMINNOTFOUND: 'Admin not found',
        PASSWORDNOTCURRECT: 'Password not correct',
        LOGINSUCCESS: 'Login success',
        SERVERERR: "Server Error",
        DATANOTFOUND: "Data not found",
        DATAFOUND: "Data founded",
        PLEASETRYLATER: "Please try later",
        DATANOTCREATED: "Data not created",
        DATACREATED: "Data created",
        ADMINEXIST: "This admin is already exists!..",
        SESSIONEXIST: "You already have existing session please logout, Then try again",
        DATAUPDATED: "Data updated",
        DATANOTUPDATED: "Data not update",
        LOGOUTED: 'Logout success',
        OTPSENT: 'Otp sent to your mobile number',
        OTPNOTSENT: 'Otp not sent to your mobile number! Please try again',
        VALIDATESUCCESS: 'Validation success',
        VALIDATEFAILURE: 'Validation failed',
        IMAGEUPLOADED: 'Image uploaded',
        DATADELETED: 'Data removed',
        DATANOTDELETED: 'Data not removed',
        NOTAUTH: 'You are not allowed to access this request. || User not exist.',
        NOTALLOWANYONE: 'This API not allowed any one',
        PROVIDEVALIDADMIN: 'Please provide valid admin with valid roles',
        OLDPASSWRONG: 'Old password is incorrect',
        PASSWORDRESETED: 'Your password is resetted',
        USERNOTFOUND: 'User not found',
        ZONENOTFOUND: 'Zone not found',
        MOBILENUMBERMAN: 'Mobile number or email are mandatory, Please enter your mobile number or email',
        SUCCESS: 'Success',
        FAILED: 'Failed' ,
        CARNOTFOUND: 'Car not found or Car has existing booking, Cars Id: ',
        SERVICENOTFOUND: 'Service not found, Service Id: ',
        TIMENOTFOUND: 'Time slot not found, TimeSlot Id: ',
        ADDRESSNOTFOUND: 'Address not found, Address Id: ',
        USERBLOCKED: 'Your not able to get the service, Your are blocked',
        PRODUCTNOTFOUND: 'Product not found, Product Id: ',
        NOTABLETOEDITORDER: 'Your not able to edit the order, Rider started their rides for you',
        ORDERNOTFOUND: 'Order not exist',
        ALREADYONLIVE: 'You are already online',
        ALREADYOFFLIVE: 'You are already offline',
        LOCATIONNOTFOUND: 'Your location not found',
        AGENTNOTFOUND: 'Agent not found',
        AGENTNOTEITHORDER: 'Agent missmatch with the order, This order is not handled by this agent',
        AREANOTSERVICABLE: 'Unserviceable area',
        AGENTFOUND: 'Agent found',
        AGENTEXIST: 'Agent mobile already exist',
        AGENTNOTACIVE: 'You are not an active agent',
        STATUSNEEDED: "Status needed",
        WORKNOTSTARTED: 'Work not started yet',
        PROVIDEUSERTYPE: 'Please provide user type',
        PROVIDEVALID: 'Please provide valid type',
        SMSTRIGERTED: 'SMS triggered',
        ERRORONVALIDATION: "Error on validator",
        VALIDATIONERROR: "Validation error. keys: ",
        VALIDATIONSUCCESS: "Validation seccess",
        VALIDSUBSCRIPTION: "Enter valid subscription",
        ALREADYEX: "Email or Mobile already exist our database",
        INVALIDTASK: "Invalid task, The give task is not in the state of accept any offer",
        INVALIDOFFER: "Invalid offer, This offer has been canceled or its not a valid offer",
        INVALIDOFFFORSTART: "Invalid offer, This offer may not be accepted by user or not yet paid",
        INVALIDTASKSTART: "Invalid task, This task is not the valid to start the work",
        YOURNOTALLOW: "Not allowed: You can't able to post a review for yourself",
        NOTABLETORATE: "Not allowed: You are not a right person to review (or) review already posted for this user",
        YOUCANT: "Not allowed: You are not allowed to make offer! You are the owner of this project",
        CANTREPLAY: "Not allowed: You are not authorized person to replay",
        CANTPOSTQUESTION: "Not allowed: Your are not allowed to post questions (or) Invalid task id",
        CANTANSWER: "Not allowed: Your are not allowed to post answer (or) Invalid task id (or) Invalid post id"
    },
    ar: {
        USERFOUND: "User found",
        ADMINNOTFOUND: 'Admin not found',
        PASSWORDNOTCURRECT: 'Password not correct',
        LOGINSUCCESS: 'Login success',
        SERVERERR: "Server Error",
        DATANOTFOUND: "Data not found",
        DATAFOUND: "Data founded",
        PLEASETRYLATER: "Please try later",
        DATANOTCREATED: "Data not created",
        DATACREATED: "Data created",
        ADMINEXIST: "This admin is already exists!..",
        SESSIONEXIST: "You already have existing session please logout, Then try again",
        DATAUPDATED: "Data updated",
        DATANOTUPDATED: "Data not update",
        LOGOUTED: 'Logout success',
        OTPSENT: 'Otp sent to your mobile number',
        OTPNOTSENT: 'Otp not sent to your mobile number! Please try again',
        VALIDATESUCCESS: 'Validation success',
        VALIDATEFAILURE: 'Validation failed',
        IMAGEUPLOADED: 'Image uploaded',
        DATADELETED: 'Data removed',
        DATANOTDELETED: 'Data not removed',
        NOTAUTH: 'You are not allowed to access this request. || User not exist.',
        NOTALLOWANYONE: 'This API not allowed any one',
        PROVIDEVALIDADMIN: 'Please provide valid admin with valid roles',
        OLDPASSWRONG: 'Old password is incorrect',
        PASSWORDRESETED: 'Your password is resetted',
        USERNOTFOUND: 'User not found',
        ZONENOTFOUND: 'Zone not found',
        MOBILENUMBERMAN: 'Mobile number or email are mandatory, Please enter your mobile number or email',
        SUCCESS: 'Success',
        FAILED: 'Failed' ,
        CARNOTFOUND: 'Car not found or Car has existing booking, Cars Id: ',
        SERVICENOTFOUND: 'Service not found, Service Id: ',
        TIMENOTFOUND: 'Time slot not found, TimeSlot Id: ',
        ADDRESSNOTFOUND: 'Address not found, Address Id: ',
        USERBLOCKED: 'Your not able to get the service, Your are blocked',
        PRODUCTNOTFOUND: 'Product not found, Product Id: ',
        NOTABLETOEDITORDER: 'Your not able to edit the order, Rider started their rides for you',
        ORDERNOTFOUND: 'Order not exist',
        ALREADYONLIVE: 'You are already online',
        ALREADYOFFLIVE: 'You are already offline',
        LOCATIONNOTFOUND: 'Your location not found',
        AGENTNOTFOUND: 'Agent not found',
        AGENTNOTEITHORDER: 'Agent missmatch with the order, This order is not handled by this agent',
        AREANOTSERVICABLE: 'Unserviceable area',
        AGENTFOUND: 'Agent found',
        AGENTEXIST: 'Agent mobile already exist',
        AGENTNOTACIVE: 'You are not an active agent',
        STATUSNEEDED: "Status needed",
        WORKNOTSTARTED: 'Work not started yet',
        PROVIDEUSERTYPE: 'Please provide user type',
        PROVIDEVALID: 'Please provide valid type',
        SMSTRIGERTED: 'SMS triggered',
        ERRORONVALIDATION: "Error on validator",
        VALIDATIONERROR: "Validation error. keys: ",
        VALIDATIONSUCCESS: "Validation seccess",
        VALIDSUBSCRIPTION: "Enter valid subscription",
        ALREADYEX: "Email or Mobile already exist our database",
        INVALIDTASK: "Invalid task, The give task is not in the state of accept any offer",
        INVALIDOFFER: "Invalid offer, This offer has been canceled or its not a valid offer",
        INVALIDOFFFORSTART: "Invalid offer, This offer may not be accepted by user or not yet paid",
        INVALIDTASKSTART: "Invalid task, This task is not the valid to start the work",
        YOURNOTALLOW: "Not allowed: You can't able to post a review for yourself",
        NOTABLETORATE: "Not allowed: You are not a right person to review (or) review already posted for this user",
        YOUCANT: "Not allowed: You are not allowed to make offer! You are the owner of this project",
        CANTREPLAY: "Not allowed: You are not authorized person to replay",
        CANTPOSTQUESTION: "Not allowed: Your are not allowed to post questions (or) Invalid task id",
        CANTANSWER: "Not allowed: Your are not allowed to post answer (or) Invalid task id (or) Invalid post id"

    }
};